[package]
name = "BrrConv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

anyhow = "1.0.51"
hound = "3.4.0"
indicatif = "0.16.2"
nibble_vec = "0.1.0"